name: Manual Release APK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version，For example v1.0.0"
        required: true
        type: string
      title:
        description: "Release Title"
        required: true
        default: "silent-pass"
        type: string
      notes:
        description: "Release Note"
        required: false
        default: ""
        type: string

permissions:
  contents: write

jobs:
  release:
    name: Build and publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate version
        run: |
          if ! echo "${{ inputs.version }}" | grep -Eq '^v[0-9]+(\.[0-9]+){2}$'; then
            echo "The version number format is incorrect. Please use v1.0.0"
            exit 1
          fi

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build release APK
        run: ./gradlew :app:assembleRelease

      - name: Prepare APK
        run: |
          mkdir -p release
          cp app/build/outputs/apk/release/app-release.apk \
            release/silent-call-${{ inputs.version }}.apk

      - name: Create and push tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git ls-remote --exit-code --tags origin "refs/tags/${{ inputs.version }}" >/dev/null 2>&1; then
            echo "Tag ${{ inputs.version }} already exists."
          else
            git tag -a "${{ inputs.version }}" -m "${{ inputs.title }} ${{ inputs.version }}"
            git push origin "${{ inputs.version }}"
          fi

      - name: Create release notes
        env:
          RELEASE_NOTES: ${{ inputs.notes }}
        run: |
          if [ -z "$RELEASE_NOTES" ]; then
            RELEASE_NOTES="SilentCall ${{ inputs.version }}"
          fi
          printf "%s\n" "$RELEASE_NOTES" > release-notes.md

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ inputs.version }}" \
            release/silent-call-${{ inputs.version }}.apk \
            --title "${{ inputs.title }} ${{ inputs.version }}" \
            --notes-file release-notes.md

      - name: Upload workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: silent-call-${{ inputs.version }}
          path: release/*
